server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.example.com/realms/myrealm}

logging:
  level:
    org.springframework.security: INFO
